### ISSUE TITLE
Found back my r0ket

### ISSUE THREAD

**Issue by voidzero** [r0ket/r0ket#47]
Hi,

I was cleaning up my attic and found my r0ket and flame back! From the good old 2011 congress. 
I am trying to turn it on but the power switch is a bit broken so I guess I need to replace it. Does anyone know which component I can use?

Thanks
Mark

**Comment by schneider42** [comment]
The original switch is a JS102011SAQN : https://www.digikey.de/en/products/detail/c-k/JS102011SAQN/1640114

You can also simply replace the switch with a 1x3 pinheader and use a jumper to make the contact. At least that is what people back in the day did.

Awesome to see you giving you r0ket some love :)

**Comment by voidzero** [comment]
> The original switch is a JS102011SAQN : https://www.digikey.de/en/products/detail/c-k/JS102011SAQN/1640114
> 
> You can also simply replace the switch with a 1x3 pinheader and use a jumper to make the contact. At least that is what people back in the day did.
> 
> Awesome to see you giving you r0ket some love :)

Hey @schneider42 thanks for your reply! Sorry I missed it earlier. Now I can fix it and indeed give it some love. Any idea if there is anywhere I can get a flame for it? That would really make it complete. I have one flame now but two r0kets, they used to sell them at pollin.de so I got a spare one 😁
